### ISSUE TITLE
https://realtime.justyo.co <= Doesn't work

### ISSUE THREAD

**Issue by LukyVj** [YoApp/counter#3]
Hey guys ! 

I wanted to check the Realtime YO website, but the url obviously doesn't work.

**Comment by LukyVj** [comment]
Oops, it seems all the YO websites arn't working anymore. 
Issue closed..

**Comment by zachlatta** [comment]
Hmm? The websites look up to me.

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

On Wed, Sep 10, 2014, at 08:02 PM, Lucas Bonomi wrote:

  Closed [1]#3.

  —
  Reply to this email directly or [2]view it on GitHub.

References
1. https://github.com/YoApp/counter/issues/3
2. https://github.com/YoApp/counter/issues/3#event-164010333
